http:
    middlewares:
        prometheus-auth:
            basicAuth:
                users:
                    - "remote:$2y$05$wKWWmaizCtZTHkk5hYWo3.Tu1LCNZNjhytOrk4FyYwVq5BelMTP/S"
        loki-auth:
            basicAuth:
                users:
                    - "remote:$2y$05$wKWWmaizCtZTHkk5hYWo3.Tu1LCNZNjhytOrk4FyYwVq5BelMTP/S"
        grafana-auth:
            basicAuth:
                users:
                    - "remote:$2y$05$wKWWmaizCtZTHkk5hYWo3.Tu1LCNZNjhytOrk4FyYwVq5BelMTP/S"
