apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${PROMETHEUS_BASE_URL}:${PROMETHEUS_PORT}
    isDefault: true
    basicAuth: true
    basicAuthUser: ${PROMETHEUS_USERNAME}
    basicAuthPassword: ${PROMETHEUS_PASSWORD}
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: 'http://${LOKI_BASE_URL}:${LOKI_PORT}'
    version: 1
    editable: true
    basicAuth: true
    basicAuthUser: ${LOKI_USERNAME}
    basicAuthPassword: ${LOKI_PASSWORD}